name: ci_client

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    path:
      - "client/**"

jobs:
  deploye:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
          - iOS
          - Android
          - WebGL
    steps:
      - uses: actions/checkout@v2

      - name: client builder
        uses: 